server:
  port: 8549
spring:
  application:
    name: spring-boot-tutorial
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/soho3q?characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
  rabbitmq:
    host: 127.0.0.1
    port: 5678
    username: guest
    password: guest
  jackson:
    serialization:
      write-dates-as-timestamps: true  #使用数值timestamp表示日期

mybatis:
  # type-aliases扫描路径
  type-aliases-package: com.tm.codemapping.bean,com.tm.system.bean
  check-config-location: true
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml
    
#mappers 多个接口时逗号隔开
mapper:
  mappers: com.tm.codemapping.config.MyMapper
  not-empty: false
  identity: MYSQL
  order: after
 
#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
netty:
  tcp: 
    port: 11236
  # bossGroup的线程数
  boss:
    thread:
      count: 2
  # worker的线程数
  worker:
    thread:
      count: 2
  #是否使用长连接
  so:
    keepalive: true
    backlog: 100
      
logging:
  file: target/app.log
  level:
    ROOT: WARN
    com.tm: TRACE
    com.tm.codemapping.mapper: WARN
    
#此项目的自定义属性  
tutorial:
  uploadFolder: target/upload-files/    #文件上传目录，可以用/开头的绝对路径