server:
  port: 8549
spring:
  application:
    name: spring-boot-tutorial
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/soho3q?characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
  jackson:
    serialization:
      write-dates-as-timestamps: true  #使用数值timestamp表示日期

mybatis:
  check-config-location: true
  config-location: classpath:/mybatis-config.xml

logging:
  file: target/app.log
  level:
    ROOT: WARN
    com.tm: TRACE
    com.tm.codemapping.mapper: WARN
    
#此项目的自定义属性  
tutorial:
  uploadFolder: target/upload-files/    #文件上传目录，可以用/开头的绝对路径